import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Navbar from "@/components/Navbar";
import { getNavbarData } from "@/data/data";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Starter Agency",
  description: "Generated by Juhh",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navbarData = await getNavbarData();

  return (
    <html lang="fr">
      <body className={inter.className}>
        <Navbar data={navbarData} />
        {children}
      </body>
    </html>
  );
}
